-- huntbuddy/zones.lua
-- Zone data for HuntBuddy (Batch 1 of 300+)

local zones = {
    zones = {
        {shortName = "abysmal", fullName = "Abysmal Sea", zem = { emu = 1.00, live = "--" }, levelMin = 50, levelMax = 70, expansion = "PoP", isHotzone = false, isCity = false},
        {shortName = "acrylia", fullName = "Acrylia Caverns", zem = { emu = 2.00, live = "--" }, levelMin = 45, levelMax = 60, expansion = "Luclin", isHotzone = true, isCity = false},
        {shortName = "airplane", fullName = "Plane of Sky", zem = { emu = 1.13, live = "--" }, levelMin = 45, levelMax = 60, expansion = "Classic", isHotzone = false, isCity = false},
        {shortName = "akanon", fullName = "Ak'Anon", zem = { emu = 1.33, live = "--" }, levelMin = 1, levelMax = 20, expansion = "Classic", isHotzone = false, isCity = true},
        {shortName = "akheva", fullName = "Akheva Ruins", zem = { emu = 1.75, live = "--" }, levelMin = 50, levelMax = 65, expansion = "Luclin", isHotzone = true, isCity = false},
        {shortName = "anguish", fullName = "Anguish, the Fallen Palace", zem = { emu = 1.00, live = "--" }, levelMin = 65, levelMax = 75, expansion = "OoW", isHotzone = false, isCity = false},
        {shortName = "apprentice", fullName = "Apprentice Ring", zem = { emu = 1.00, live = "--" }, levelMin = 1, levelMax = 10, expansion = "Classic", isHotzone = false, isCity = false},
        {shortName = "arcstone", fullName = "Arcstone, Isle of Spirits", zem = { emu = 1.00, live = "--" }, levelMin = 65, levelMax = 75, expansion = "DoDh", isHotzone = false, isCity = false},
        {shortName = "arena", fullName = "The Arena", zem = { emu = 1.00, live = "--" }, levelMin = 1, levelMax = 100, expansion = "Classic", isHotzone = false, isCity = true},
        {shortName = "arena2", fullName = "Arena Two", zem = { emu = 1.00, live = "--" }, levelMin = 1, levelMax = 100, expansion = "Classic", isHotzone = false, isCity = false},
        {shortName = "arttest", fullName = "Art Testing Domain", zem = { emu = 1.00, live = "--" }, levelMin = 1, levelMax = 100, expansion = "Classic", isHotzone = false, isCity = false},
        {shortName = "ashengate", fullName = "Ashengate, Reliquary of the Scale", zem = { emu = 1.00, live = "--" }, levelMin = 70, levelMax = 80, expansion = "TSS", isHotzone = false, isCity = false},
        {shortName = "atiiki", fullName = "Jewel of Atiiki", zem = { emu = 1.00, live = "--" }, levelMin = 70, levelMax = 80, expansion = "TBS", isHotzone = false, isCity = false},
        {shortName = "aviak", fullName = "Aviak Village", zem = { emu = 1.00, live = "--" }, levelMin = 10, levelMax = 25, expansion = "Classic", isHotzone = false, isCity = false},
        {shortName = "barindu", fullName = "Barindu, Hanging Gardens", zem = { emu = 2.00, live = "--" }, levelMin = 60, levelMax = 70, expansion = "GoD", isHotzone = true, isCity = false},
        {shortName = "barren", fullName = "Barren Coast", zem = { emu = 1.00, live = "--" }, levelMin = 50, levelMax = 65, expansion = "TBS", isHotzone = false, isCity = false},
        {shortName = "barter", fullName = "Barter Hall", zem = { emu = 1.00, live = "--" }, levelMin = 1, levelMax = 100, expansion = "Live", isHotzone = false, isCity = true},
        {shortName = "bazaar", fullName = "The Bazaar", zem = { emu = 1.00, live = "--" }, levelMin = 1, levelMax = 100, expansion = "Luclin", isHotzone = false, isCity = true},
        {shortName = "befallen", fullName = "Befallen", zem = { emu = 2.13, live = "--" }, levelMin = 5, levelMax = 25, expansion = "Classic", isHotzone = true, isCity = false},
        {shortName = "befallenb", fullName = "Befallen Depths", zem = { emu = 1.00, live = "--" }, levelMin = 10, levelMax = 30, expansion = "Classic", isHotzone = false, isCity = false},
        {shortName = "beholder", fullName = "Gorge of King Xorbb", zem = { emu = 1.00, live = "--" }, levelMin = 10, levelMax = 25, expansion = "Classic", isHotzone = false, isCity = false},
        {shortName = "bertoxtemple", fullName = "Temple of Bertoxxulous", zem = { emu = 1.50, live = "--" }, levelMin = 65, levelMax = 75, expansion = "DoDh", isHotzone = true, isCity = false},
        {shortName = "blackburrow", fullName = "Blackburrow", zem = { emu = 1.33, live = "--" }, levelMin = 5, levelMax = 20, expansion = "Classic", isHotzone = true, isCity = false},
        {shortName = "blacksail", fullName = "Blacksail Folly", zem = { emu = 1.00, live = "--" }, levelMin = 60, levelMax = 75, expansion = "TBS", isHotzone = false, isCity = false},
        {shortName = "bloodfields", fullName = "The Bloodfields", zem = { emu = 2.00, live = "--" }, levelMin = 55, levelMax = 70, expansion = "GoD", isHotzone = true, isCity = false},
        {shortName = "bloodmoon", fullName = "Bloodmoon Keep", zem = { emu = 1.00, live = "--" }, levelMin = 75, levelMax = 85, expansion = "SoF", isHotzone = false, isCity = false},
        {shortName = "bothunder", fullName = "Bastion of Thunder", zem = { emu = 2.75, live = "--" }, levelMin = 60, levelMax = 70, expansion = "PoP", isHotzone = true, isCity = false},
        {shortName = "broodlands", fullName = "The Broodlands", zem = { emu = 1.75, live = "--" }, levelMin = 50, levelMax = 65, expansion = "DoN", isHotzone = true, isCity = false},
        {shortName = "buriedsea", fullName = "Buried Sea", zem = { emu = 1.00, live = "--" }, levelMin = 60, levelMax = 75, expansion = "TBS", isHotzone = false, isCity = false},
        {shortName = "burningwood", fullName = "Burning Woods", zem = { emu = 1.00, live = "--" }, levelMin = 35, levelMax = 50, expansion = "RoK", isHotzone = false, isCity = false},
        {shortName = "butcher", fullName = "Butcherblock Mountains", zem = { emu = 1.00, live = "--" }, levelMin = 1, levelMax = 20, expansion = "Classic", isHotzone = false, isCity = false},
        {shortName = "cabeast", fullName = "Cabilis East", zem = { emu = 1.33, live = "--" }, levelMin = 1, levelMax = 20, expansion = "RoK", isHotzone = false, isCity = true},
        {shortName = "cabwest", fullName = "Cabilis West", zem = { emu = 1.33, live = "--" }, levelMin = 1, levelMax = 20, expansion = "RoK", isHotzone = false, isCity = true},
        {shortName = "cauldron", fullName = "Dagnor's Cauldron", zem = { emu = 1.00, live = "--" }, levelMin = 10, levelMax = 25, expansion = "Classic", isHotzone = false, isCity = false},
        {shortName = "causeway", fullName = "Natimbi, The Broken Shores", zem = { emu = 2.25, live = "--" }, levelMin = 40, levelMax = 60, expansion = "GoD", isHotzone = true, isCity = false},
        {shortName = "cazicthule", fullName = "Cazic-Thule", zem = { emu = 1.13, live = "--" }, levelMin = 20, levelMax = 45, expansion = "Classic", isHotzone = false, isCity = false},
        {shortName = "chambersa", fullName = "Ruins of Illsalin", zem = { emu = 1.00, live = "--" }, levelMin = 65, levelMax = 75, expansion = "DoDh", isHotzone = false, isCity = false},
        {shortName = "chambersb", fullName = "Dreadspire Depths", zem = { emu = 1.00, live = "--" }, levelMin = 65, levelMax = 75, expansion = "DoDh", isHotzone = false, isCity = false},
        {shortName = "chambersc", fullName = "Illsalin Marketplace", zem = { emu = 1.00, live = "--" }, levelMin = 65, levelMax = 75, expansion = "DoDh", isHotzone = false, isCity = false},
        {shortName = "chambersd", fullName = "Temple of the Korlach", zem = { emu = 1.00, live = "--" }, levelMin = 65, levelMax = 75, expansion = "DoDh", isHotzone = false, isCity = false},
        {shortName = "chamberse", fullName = "Caverns of the Forgotten", zem = { emu = 1.00, live = "--" }, levelMin = 65, levelMax = 75, expansion = "DoDh", isHotzone = false, isCity = false},
        {shortName = "chambersf", fullName = "Lair of the Fallen", zem = { emu = 1.00, live = "--" }, levelMin = 65, levelMax = 75, expansion = "DoDh", isHotzone = false, isCity = false},
        {shortName = "charasis", fullName = "Howling Stones", zem = { emu = 1.13, live = "--" }, levelMin = 40, levelMax = 60, expansion = "RoK", isHotzone = false, isCity = false},
        {shortName = "chardok", fullName = "Chardok", zem = { emu = 1.50, live = "--" }, levelMin = 40, levelMax = 60, expansion = "RoK", isHotzone = true, isCity = false},
        {shortName = "chardokb", fullName = "Chardok: Halls of Betrayal", zem = { emu = 2.00, live = "--" }, levelMin = 45, levelMax = 65, expansion = "RoK", isHotzone = true, isCity = false},
        {shortName = "citymist", fullName = "City of Mist", zem = { emu = 0.85, live = "--" }, levelMin = 35, levelMax = 50, expansion = "RoK", isHotzone = false, isCity = false},
        {shortName = "clz", fullName = "Crescent Reach Landing Zone", zem = { emu = 1.00, live = "--" }, levelMin = 1, levelMax = 20, expansion = "TSS", isHotzone = false, isCity = false},
        {shortName = "cobaltscar", fullName = "Cobalt Scar", zem = { emu = 1.00, live = "--" }, levelMin = 35, levelMax = 50, expansion = "Velious", isHotzone = false, isCity = false},
        {shortName = "codecay", fullName = "Crypt of Decay", zem = { emu = 2.35, live = "--" }, levelMin = 55, levelMax = 65, expansion = "PoP", isHotzone = true, isCity = false},
        {shortName = "commonlands", fullName = "Commonlands", zem = { emu = 1.00, live = "--" }, levelMin = 1, levelMax = 20, expansion = "Classic", isHotzone = false, isCity = false},
        {shortName = "commons", fullName = "West Commonlands", zem = { emu = 1.00, live = "--" }, levelMin = 1, levelMax = 20, expansion = "Classic", isHotzone = false, isCity = false},
        {shortName = "corathus", fullName = "Corathus Creep", zem = { emu = 1.00, live = "--" }, levelMin = 45, levelMax = 60, expansion = "DoDh", isHotzone = false, isCity = false},
        {shortName = "corathusa", fullName = "Corathus Mines", zem = { emu = 1.00, live = "--" }, levelMin = 45, levelMax = 60, expansion = "DoDh", isHotzone = false, isCity = false},
        {shortName = "corathusb", fullName = "Corathus Lair", zem = { emu = 1.00, live = "--" }, levelMin = 45, levelMax = 60, expansion = "DoDh", isHotzone = false, isCity = false},
        {shortName = "crescent", fullName = "Crescent Reach", zem = { emu = 1.00, live = "--" }, levelMin = 1, levelMax = 20, expansion = "TSS", isHotzone = false, isCity = true},
        {shortName = "crushbone", fullName = "Crushbone", zem = { emu = 2.13, live = "--" }, levelMin = 5, levelMax = 20, expansion = "Classic", isHotzone = true, isCity = false},
        {shortName = "cryptofshade", fullName = "Crypt of Shade", zem = { emu = 1.00, live = "--" }, levelMin = 70, levelMax = 85, expansion = "SoF", isHotzone = false, isCity = false},
        {shortName = "crystal", fullName = "Crystal Caverns", zem = { emu = 1.13, live = "--" }, levelMin = 25, levelMax = 40, expansion = "Velious", isHotzone = false, isCity = false},
        {shortName = "crystallos", fullName = "Crystallos, Lair of the Awakened", zem = { emu = 1.00, live = "--" }, levelMin = 75, levelMax = 85, expansion = "SoF", isHotzone = false, isCity = false},
        {shortName = "cshome", fullName = "Crescent Shore Home", zem = { emu = 1.00, live = "--" }, levelMin = 1, levelMax = 100, expansion = "TSS", isHotzone = false, isCity = false},
        {shortName = "dalnir", fullName = "Dalnir", zem = { emu = 1.13, live = "--" }, levelMin = 25, levelMax = 40, expansion = "RoK", isHotzone = false, isCity = false},
        {shortName = "dawnshroud", fullName = "Dawnshroud Peaks", zem = { emu = 1.75, live = "--" }, levelMin = 25, levelMax = 45, expansion = "Luclin", isHotzone = true, isCity = false},
        {shortName = "deadbone", fullName = "Deadbone Reef", zem = { emu = 1.00, live = "--" }, levelMin = 60, levelMax = 75, expansion = "TBS", isHotzone = false, isCity = false},
        {shortName = "delvea", fullName = "Thundercrest Isles", zem = { emu = 2.95, live = "--" }, levelMin = 60, levelMax = 70, expansion = "DoN", isHotzone = true, isCity = false},
        {shortName = "delveb", fullName = "The Nest", zem = { emu = 2.95, live = "--" }, levelMin = 60, levelMax = 70, expansion = "DoN", isHotzone = true, isCity = false},
        {shortName = "devastation", fullName = "The Devastation", zem = { emu = 1.00, live = "--" }, levelMin = 65, levelMax = 75, expansion = "PoR", isHotzone = false, isCity = false},
        {shortName = "devastationa", fullName = "Devastation Annex", zem = { emu = 1.00, live = "--" }, levelMin = 65, levelMax = 75, expansion = "PoR", isHotzone = false, isCity = false},
        {shortName = "direwind", fullName = "Direwind Cliffs", zem = { emu = 1.00, live = "--" }, levelMin = 70, levelMax = 80, expansion = "TSS", isHotzone = false, isCity = false},
        {shortName = "discord", fullName = "Discord", zem = { emu = 1.50, live = "--" }, levelMin = 65, levelMax = 75, expansion = "OoW", isHotzone = true, isCity = false},
        {shortName = "discordtower", fullName = "Tower of Discord", zem = { emu = 1.50, live = "--" }, levelMin = 65, levelMax = 75, expansion = "OoW", isHotzone = true, isCity = false},
        {shortName = "drachnidhive", fullName = "Drachnid Hive", zem = { emu = 1.00, live = "--" }, levelMin = 65, levelMax = 75, expansion = "DoDh", isHotzone = false, isCity = false},
        {shortName = "drachnidhivea", fullName = "Drachnid Hive: East Wing", zem = { emu = 1.00, live = "--" }, levelMin = 65, levelMax = 75, expansion = "DoDh", isHotzone = false, isCity = false},
        {shortName = "drachnidhiveb", fullName = "Drachnid Hive: West Wing", zem = { emu = 1.00, live = "--" }, levelMin = 65, levelMax = 75, expansion = "DoDh", isHotzone = false, isCity = false},
        {shortName = "drachnidhivec", fullName = "Drachnid Hive: Central", zem = { emu = 1.00, live = "--" }, levelMin = 65, levelMax = 75, expansion = "DoDh", isHotzone = false, isCity = false},
        {shortName = "dragonscale", fullName = "Dragonscale Hills", zem = { emu = 1.00, live = "--" }, levelMin = 70, levelMax = 80, expansion = "SoF", isHotzone = false, isCity = false},
        {shortName = "dragonscaleb", fullName = "Dragonscale Depths", zem = { emu = 1.50, live = "--" }, levelMin = 70, levelMax = 80, expansion = "SoF", isHotzone = true, isCity = false},
        {shortName = "dranik", fullName = "Dranik's Scar", zem = { emu = 1.75, live = "--" }, levelMin = 40, levelMax = 60, expansion = "OoW", isHotzone = true, isCity = false},
        {shortName = "dranikcatacombsa", fullName = "Dranik Catacombs A", zem = { emu = 1.75, live = "--" }, levelMin = 45, levelMax = 65, expansion = "OoW", isHotzone = true, isCity = false},
        {shortName = "dranikcatacombsb", fullName = "Dranik Catacombs B", zem = { emu = 1.75, live = "--" }, levelMin = 45, levelMax = 65, expansion = "OoW", isHotzone = true, isCity = false},
        {shortName = "dranikcatacombsc", fullName = "Dranik Catacombs C", zem = { emu = 1.75, live = "--" }, levelMin = 45, levelMax = 65, expansion = "OoW", isHotzone = true, isCity = false},
        {shortName = "dranikhollowsa", fullName = "Dranik Hollows A", zem = { emu = 1.75, live = "--" }, levelMin = 45, levelMax = 65, expansion = "OoW", isHotzone = true, isCity = false},
        {shortName = "dranikhollowsb", fullName = "Dranik Hollows B", zem = { emu = 1.75, live = "--" }, levelMin = 45, levelMax = 65, expansion = "OoW", isHotzone = true, isCity = false},
        {shortName = "dranikhollowsc", fullName = "Dranik Hollows C", zem = { emu = 1.75, live = "--" }, levelMin = 45, levelMax = 65, expansion = "OoW", isHotzone = true, isCity = false},
        {shortName = "draniksewersa", fullName = "Dranik Sewers A", zem = { emu = 1.75, live = "--" }, levelMin = 45, levelMax = 65, expansion = "OoW", isHotzone = true, isCity = false},
        {shortName = "draniksewersb", fullName = "Dranik Sewers B", zem = { emu = 1.75, live = "--" }, levelMin = 45, levelMax = 65, expansion = "OoW", isHotzone = true, isCity = false},
        {shortName = "draniksewersc", fullName = "Dranik Sewers C", zem = { emu = 1.75, live = "--" }, levelMin = 45, levelMax = 65, expansion = "OoW", isHotzone = true, isCity = false},
        {shortName = "draniksscar", fullName = "Dranik's Scar", zem = { emu = 1.75, live = "--" }, levelMin = 40, levelMax = 60, expansion = "OoW", isHotzone = true, isCity = false},
        {shortName = "dreadlands", fullName = "Dreadlands", zem = { emu = 1.00, live = "--" }, levelMin = 35, levelMax = 50, expansion = "RoK", isHotzone = false, isCity = false},
        {shortName = "dreadspire", fullName = "Dreadspire Keep", zem = { emu = 1.00, live = "--" }, levelMin = 65, levelMax = 75, expansion = "DoDh", isHotzone = false, isCity = false},
        {shortName = "droga", fullName = "Temple of Droga", zem = { emu = 0.95, live = "--" }, levelMin = 35, levelMax = 50, expansion = "RoK", isHotzone = false, isCity = false},
        {shortName = "dulak", fullName = "Dulak's Harbor", zem = { emu = 2.00, live = "--" }, levelMin = 40, levelMax = 55, expansion = "Luclin", isHotzone = true, isCity = false},
        {shortName = "eastkarana", fullName = "Eastern Karana", zem = { emu = 1.00, live = "--" }, levelMin = 10, levelMax = 25, expansion = "Classic", isHotzone = false, isCity = false},
        {shortName = "eastkorlach", fullName = "East Korlach Plains", zem = { emu = 1.00, live = "--" }, levelMin = 45, levelMax = 60, expansion = "DoDh", isHotzone = false, isCity = false},
        {shortName = "eastkorlacha", fullName = "East Korlach Depths", zem = { emu = 1.00, live = "--" }, levelMin = 45, levelMax = 60, expansion = "DoDh", isHotzone = false, isCity = false},
        {shortName = "eastwastes", fullName = "Eastern Wastes", zem = { emu = 1.00, live = "--" }, levelMin = 30, levelMax = 45, expansion = "Velious", isHotzone = false, isCity = false},
        {shortName = "echo", fullName = "Echo Caverns", zem = { emu = 1.06, live = "--" }, levelMin = 20, levelMax = 40, expansion = "Luclin", isHotzone = false, isCity = false},
        {shortName = "ecommons", fullName = "East Commonlands", zem = { emu = 1.00, live = "--" }, levelMin = 1, levelMax = 20, expansion = "Classic", isHotzone = false, isCity = false},
        {shortName = "elddar", fullName = "Elddar Forest", zem = { emu = 1.00, live = "--" }, levelMin = 65, levelMax = 75, expansion = "PoR", isHotzone = false, isCity = false},
        {shortName = "elddara", fullName = "Elddar Ruins", zem = { emu = 1.00, live = "--" }, levelMin = 65, levelMax = 75, expansion = "PoR", isHotzone = false, isCity = false},
        {shortName = "emeraldjungle", fullName = "Emerald Jungle", zem = { emu = 1.00, live = "--" }, levelMin = 30, levelMax = 45, expansion = "RoK", isHotzone = false, isCity = false},
        {shortName = "erudnext", fullName = "Erudin", zem = { emu = 1.33, live = "--" }, levelMin = 1, levelMax = 20, expansion = "Classic", isHotzone = false, isCity = true},
        {shortName = "erudnint", fullName = "Erudin Palace", zem = { emu = 1.33, live = "--" }, levelMin = 1, levelMax = 20, expansion = "Classic", isHotzone = false, isCity = true},
        {shortName = "erudsxing", fullName = "Erud's Crossing", zem = { emu = 1.00, live = "--" }, levelMin = 5, levelMax = 20, expansion = "Classic", isHotzone = false, isCity = false},
        {shortName = "erudsxing2", fullName = "Erud's Crossing Depths", zem = { emu = 1.00, live = "--" }, levelMin = 5, levelMax = 20, expansion = "Classic", isHotzone = false, isCity = false},
        {shortName = "everfrost", fullName = "Everfrost Peaks", zem = { emu = 1.00, live = "--" }, levelMin = 1, levelMax = 20, expansion = "Classic", isHotzone = false, isCity = false},
        {shortName = "fearplane", fullName = "Plane of Fear", zem = { emu = 1.13, live = "--" }, levelMin = 45, levelMax = 60, expansion = "Classic", isHotzone = false, isCity = false},
        {shortName = "feerrott", fullName = "The Feerrott", zem = { emu = 1.00, live = "--" }, levelMin = 1, levelMax = 20, expansion = "Classic", isHotzone = false, isCity = false},
        {shortName = "felwithea", fullName = "Felwithe North", zem = { emu = 1.33, live = "--" }, levelMin = 1, levelMax = 20, expansion = "Classic", isHotzone = false, isCity = true},
        {shortName = "felwitheb", fullName = "Felwithe South", zem = { emu = 1.33, live = "--" }, levelMin = 1, levelMax = 20, expansion = "Classic", isHotzone = false, isCity = true},
        {shortName = "ferubi", fullName = "Ferubi, Forgotten Temple", zem = { emu = 2.00, live = "--" }, levelMin = 60, levelMax = 70, expansion = "GoD", isHotzone = true, isCity = false},
        {shortName = "fhalls", fullName = "Froststone Halls", zem = { emu = 1.00, live = "--" }, levelMin = 70, levelMax = 80, expansion = "SoF", isHotzone = false, isCity = false},
        {shortName = "fieldofbone", fullName = "Field of Bone", zem = { emu = 1.00, live = "--" }, levelMin = 1, levelMax = 20, expansion = "RoK", isHotzone = false, isCity = false},
        {shortName = "firiona", fullName = "Firiona Vie", zem = { emu = 1.00, live = "--" }, levelMin = 20, levelMax = 35, expansion = "RoK", isHotzone = false, isCity = false},
        {shortName = "freeportacademy", fullName = "Freeport Academy", zem = { emu = 1.00, live = "--" }, levelMin = 1, levelMax = 20, expansion = "Classic", isHotzone = false, isCity = true},
        {shortName = "freeportarena", fullName = "Freeport Arena", zem = { emu = 1.00, live = "--" }, levelMin = 1, levelMax = 100, expansion = "Classic", isHotzone = false, isCity = true},
        {shortName = "freeportcityhall", fullName = "Freeport City Hall", zem = { emu = 1.00, live = "--" }, levelMin = 1, levelMax = 20, expansion = "Classic", isHotzone = false, isCity = true},
        {shortName = "freeporteast", fullName = "East Freeport", zem = { emu = 1.00, live = "--" }, levelMin = 1, levelMax = 20, expansion = "Classic", isHotzone = false, isCity = true},
        {shortName = "freeporthall", fullName = "Freeport Hall", zem = { emu = 1.00, live = "--" }, levelMin = 1, levelMax = 20, expansion = "Classic", isHotzone = false, isCity = true},
        {shortName = "freeportmilitia", fullName = "Freeport Militia", zem = { emu = 1.00, live = "--" }, levelMin = 1, levelMax = 20, expansion = "Classic", isHotzone = false, isCity = true},
        {shortName = "freeportsewers", fullName = "Freeport Sewers", zem = { emu = 1.00, live = "--" }, levelMin = 1, levelMax = 20, expansion = "Classic", isHotzone = false, isCity = false},
        {shortName = "freeporttemple", fullName = "Freeport Temple", zem = { emu = 1.00, live = "--" }, levelMin = 1, levelMax = 20, expansion = "Classic", isHotzone = false, isCity = true},
        {shortName = "freeporttheater", fullName = "Freeport Theater", zem = { emu = 1.00, live = "--" }, levelMin = 1, levelMax = 20, expansion = "Classic", isHotzone = false, isCity = true},
        {shortName = "freeportwest", fullName = "West Freeport", zem = { emu = 1.00, live = "--" }, levelMin = 1, levelMax = 20, expansion = "Classic", isHotzone = false, isCity = true},
        {shortName = "freporte", fullName = "East Freeport", zem = { emu = 1.00, live = "--" }, levelMin = 1, levelMax = 20, expansion = "Classic", isHotzone = false, isCity = true},
        {shortName = "freportn", fullName = "North Freeport", zem = { emu = 1.33, live = "--" }, levelMin = 1, levelMax = 20, expansion = "Classic", isHotzone = false, isCity = true},
        {shortName = "freportw", fullName = "West Freeport", zem = { emu = 1.00, live = "--" }, levelMin = 1, levelMax = 20, expansion = "Classic", isHotzone = false, isCity = true},
        {shortName = "frontiermtns", fullName = "Frontier Mountains", zem = { emu = 1.00, live = "--" }, levelMin = 25, levelMax = 45, expansion = "RoK", isHotzone = false, isCity = false},
        {shortName = "frostcrypt", fullName = "Frostcrypt, Throne of the Shade King", zem = { emu = 1.00, live = "--" }, levelMin = 70, levelMax = 80, expansion = "TSS", isHotzone = false, isCity = false},
        {shortName = "frozenshadow", fullName = "Tower of Frozen Shadow", zem = { emu = 1.13, live = "--" }, levelMin = 30, levelMax = 50, expansion = "Velious", isHotzone = false, isCity = false},
        {shortName = "fungusgrove", fullName = "Fungus Grove", zem = { emu = 2.00, live = "--" }, levelMin = 30, levelMax = 50, expansion = "Luclin", isHotzone = true, isCity = false},
        {shortName = "gfaydark", fullName = "Greater Faydark", zem = { emu = 1.00, live = "--" }, levelMin = 1, levelMax = 15, expansion = "Classic", isHotzone = false, isCity = false},
        {shortName = "greatdivide", fullName = "Great Divide", zem = { emu = 1.00, live = "--" }, levelMin = 30, levelMax = 50, expansion = "Velious", isHotzone = freeporttemplefalse, isCity = false},
        {shortName = "griegsend", fullName = "Grieg's End", zem = { emu = 0.90, live = "--" }, levelMin = 40, levelMax = 55, expansion = "Luclin", isHotzone = false, isCity = false},
        {shortName = "grimling", fullName = "Grimling Forest", zem = { emu = 1.06, live = "--" }, levelMin = 25, levelMax = 45, expansion = "Luclin", isHotzone = false, isCity = false},
        {shortName = "grobb", fullName = "Grobb", zem = { emu = 1.33, live = "--" }, levelMin = 1, levelMax = 20, expansion = "Classic", isHotzone = false, isCity = true},
        {shortName = "growthplane", fullName = "Plane of Growth", zem = { emu = 1.13, live = "--" }, levelMin = 45, levelMax = 60, expansion = "Velious", isHotzone = false, isCity = false},
        {shortName = "guardian", fullName = "Guardian of the Sands", zem = { emu = 1.00, live = "--" }, levelMin = 65, levelMax = 75, expansion = "SoF", isHotzone = false, isCity = false},
        {shortName = "guildhall", fullName = "Guild Hall", zem = { emu = 1.00, live = "--" }, levelMin = 1, levelMax = 100, expansion = "Live", isHotzone = false, isCity = true},
        {shortName = "guildlobby", fullName = "Guild Lobby", zem = { emu = 1.00, live = "--" }, levelMin = 1, levelMax = 100, expansion = "Live", isHotzone = false, isCity = true},
        {shortName = "guka", fullName = "Lower Guk: Ancient Ruins", zem = { emu = 1.50, live = "--" }, levelMin = 30, levelMax = 50, expansion = "Classic", isHotzone = true, isCity = false},
        {shortName = "gukb", fullName = "Lower Guk: Basilica", zem = { emu = 1.50, live = "--" }, levelMin = 30, levelMax = 50, expansion = "Classic", isHotzone = true, isCity = false},
        {shortName = "gukbottom", fullName = "Lower Guk", zem = { emu = 1.06, live = "--" }, levelMin = 30, levelMax = 50, expansion = "Classic", isHotzone = false, isCity = false},
        {shortName = "gukc", fullName = "Lower Guk: Caverns", zem = { emu = 1.50, live = "--" }, levelMin = 30, levelMax = 50, expansion = "Classic", isHotzone = true, isCity = false},
        {shortName = "gukd", fullName = "Lower Guk: Depths", zem = { emu = 1.50, live = "--" }, levelMin = 30, levelMax = 50, expansion = "Classic", isHotzone = true, isCity = false},
        {shortName = "guke", fullName = "Lower Guk: Elders", zem = { emu = 1.50, live = "--" }, levelMin = 30, levelMax = 50, expansion = "Classic", isHotzone = true, isCity = false},
        {shortName = "gukf", fullName = "Lower Guk: Frenzied", zem = { emu = 1.50, live = "--" }, levelMin = 30, levelMax = 50, expansion = "Classic", isHotzone = true, isCity = false},
        {shortName = "gukg", fullName = "Lower Guk: Ghouls", zem = { emu = 1.50, live = "--" }, levelMin = 30, levelMax = 50, expansion = "Classic", isHotzone = true, isCity = false},
        {shortName = "gukh", fullName = "Lower Guk: Heart", zem = { emu = 1.50, live = "--" }, levelMin = 30, levelMax = 50, expansion = "Classic", isHotzone = true, isCity = false},
        {shortName = "guktop", fullName = "Upper Guk", zem = { emu = 2.00, live = "--" }, levelMin = 5, levelMax = 25, expansion = "Classic", isHotzone = true, isCity = false},
        {shortName = "gunthak", fullName = "Gulf of Gunthak", zem = { emu = 1.50, live = "--" }, levelMin = 35, levelMax = 50, expansion = "Luclin", isHotzone = true, isCity = false},
        {shortName = "gyrospireb", fullName = "Gyrospire Beza", zem = { emu = 1.00, live = "--" }, levelMin = 75, levelMax = 85, expansion = "SoF", isHotzone = false, isCity = false},
        {shortName = "gyrospirez", fullName = "Gyrospire Zeka", zem = { emu = 1.00, live = "--" }, levelMin = 75, levelMax = 85, expansion = "SoF", isHotzone = false, isCity = false},
        {shortName = "halas", fullName = "Halas", zem = { emu = 1.33, live = "--" }, levelMin = 1, levelMax = 20, expansion = "Classic", isHotzone = false, isCity = true},
        {shortName = "harbingers", fullName = "Harbinger's Spire", zem = { emu = 2.00, live = "--" }, levelMin = 45, levelMax = 60, expansion = "OoW", isHotzone = true, isCity = false},
        {shortName = "hateplane", fullName = "Plane of Hate", zem = { emu = 1.00, live = "--" }, levelMin = 45, levelMax = 60, expansion = "Classic", isHotzone = false, isCity = false},
        {shortName = "hateplaneb", fullName = "Plane of Hate: Innoruuk's Realm", zem = { emu = 1.13, live = "--" }, levelMin = 45, levelMax = 60, expansion = "Classic", isHotzone = false, isCity = false},
        {shortName = "hatesfury", fullName = "Hate's Fury", zem = { emu = 2.00, live = "--" }, levelMin = 45, levelMax = 60, expansion = "Luclin", isHotzone = true, isCity = false},
        {shortName = "highkeep", fullName = "High Keep", zem = { emu = 2.00, live = "--" }, levelMin = 20, levelMax = 40, expansion = "Classic", isHotzone = true, isCity = false},
        {shortName = "highpass", fullName = "Highpass Hold", zem = { emu = 1.06, live = "--" }, levelMin = 15, levelMax = 30, expansion = "Classic", isHotzone = false, isCity = false},
        {shortName = "highpasshold", fullName = "Highpass Hold", zem = { emu = 1.00, live = "--" }, levelMin = 15, levelMax = 30, expansion = "Classic", isHotzone = false, isCity = false},
        {shortName = "highpasskeep", fullName = "Highpass Keep", zem = { emu = 1.00, live = "--" }, levelMin = 20, levelMax = 40, expansion = "Classic", isHotzone = false, isCity = false},
        {shortName = "hillsofshade", fullName = "Hills of Shade", zem = { emu = 1.00, live = "--" }, levelMin = 75, levelMax = 85, expansion = "SoF", isHotzone = false, isCity = false},
        {shortName = "hohonora", fullName = "Halls of Honor", zem = { emu = 2.75, live = "--" }, levelMin = 55, levelMax = 65, expansion = "PoP", isHotzone = true, isCity = false},
        {shortName = "hohonorb", fullName = "Halls of Honor: Arena", zem = { emu = 2.75, live = "--" }, levelMin = 55, levelMax = 65, expansion = "PoP", isHotzone = true, isCity = false},
        {shortName = "hole", fullName = "The Hole", zem = { emu = 1.33, live = "--" }, levelMin = 40, levelMax = 60, expansion = "Classic", isHotzone = true, isCity = false},
        {shortName = "hollowshade", fullName = "Hollowshade Moor", zem = { emu = 1.00, live = "--" }, levelMin = 20, levelMax = 40, expansion = "Luclin", isHotzone = false, isCity = false},
        {shortName = "iceclad", fullName = "Iceclad Ocean", zem = { emu = 1.00, live = "--" }, levelMin = 25, levelMax = 40, expansion = "Velious", isHotzone = false, isCity = false},
        {shortName = "icefall", fullName = "Icefall Glacier", zem = { emu = 1.00, live = "--" }, levelMin = 75, levelMax = 85, expansion = "SoF", isHotzone = false, isCity = false},
        {shortName = "ikkinz", fullName = "Ikkinz, Chambers of Destruction", zem = { emu = 1.50, live = "--" }, levelMin = 65, levelMax = 75, expansion = "GoD", isHotzone = true, isCity = false},
        {shortName = "illsalin", fullName = "Illsalin Ruins", zem = { emu = 1.00, live = "--" }, levelMin = 65, levelMax = 75, expansion = "DoDh", isHotzone = false, isCity = false},
        {shortName = "illsalina", fullName = "Illsalin Annex", zem = { emu = 1.00, live = "--" }, levelMin = 65, levelMax = 75, expansion = "DoDh", isHotzone = false, isCity = false},
        {shortName = "illsalinb", fullName = "Illsalin Depths", zem = { emu = 1.00, live = "--" }, levelMin = 65, levelMax = 75, expansion = "DoDh", isHotzone = false, isCity = false},
        {shortName = "illsalinc", fullName = "Illsalin Catacombs", zem = { emu = 1.00, live = "--" }, levelMin = 65, levelMax = 75, expansion = "DoDh", isHotzone = false, isCity = false},
        {shortName = "inktuta", fullName = "Inktu'Ta, The Unmasked Chapel", zem = { emu = 1.75, live = "--" }, levelMin = 60, levelMax = 70, expansion = "GoD", isHotzone = true, isCity = false},
        {shortName = "innothule", fullName = "Innothule Swamp", zem = { emu = 1.00, live = "--" }, levelMin = 5, levelMax = 20, expansion = "Classic", isHotzone = false, isCity = false},
        {shortName = "innothuleb", fullName = "Innothule Depths", zem = { emu = 1.00, live = "--" }, levelMin = 5, levelMax = 20, expansion = "Classic", isHotzone = false, isCity = false},
        {shortName = "jaggedpine", fullName = "Jaggedpine Forest", zem = { emu = 1.00, live = "--" }, levelMin = 20, levelMax = 40, expansion = "Classic", isHotzone = false, isCity = false},
        {shortName = "jardelshook", fullName = "Jardel's Hook", zem = { emu = 1.00, live = "--" }, levelMin = 60, levelMax = 75, expansion = "TBS", isHotzone = false, isCity = false},
        {shortName = "kael", fullName = "Kael Drakkel", zem = { emu = 1.13, live = "--" }, levelMin = 35, levelMax = 60, expansion = "Velious", isHotzone = false, isCity = true},
        {shortName = "kaesora", fullName = "Kaesora", zem = { emu = 1.46, live = "--" }, levelMin = 30, levelMax = 50, expansion = "RoK", isHotzone = true, isCity = false},
        {shortName = "kaladima", fullName = "Kaladim North", zem = { emu = 1.33, live = "--" }, levelMin = 1, levelMax = 20, expansion = "Classic", isHotzone = false, isCity = true},
        {shortName = "kaladimb", fullName = "Kaladim South", zem = { emu = 1.33, live = "--" }, levelMin = 1, levelMax = 20, expansion = "Classic", isHotzone = false, isCity = true},
        {shortName = "karnor", fullName = "Karnor's Castle", zem = { emu = 1.13, live = "--" }, levelMin = 45, levelMax = 60, expansion = "RoK", isHotzone = false, isCity = false},
        {shortName = "katta", fullName = "Katta Castellum", zem = { emu = 1.13, live = "--" }, levelMin = 30, levelMax = 50, expansion = "Luclin", isHotzone = false, isCity = true},
        {shortName = "kattacastrum", fullName = "Katta Castrum", zem = { emu = 1.00, live = "--" }, levelMin = 70, levelMax = 85, expansion = "TBS", isHotzone = false, isCity = true},
        {shortName = "kedge", fullName = "Kedge Keep", zem = { emu = 1.33, live = "--" }, levelMin = 35, levelMax = 50, expansion = "Classic", isHotzone = true, isCity = false},
        {shortName = "kerraridge", fullName = "Kerraridge", zem = { emu = 1.20, live = "--" }, levelMin = 75, levelMax = 85, expansion = "SoF", isHotzone = true, isCity = false},
        {shortName = "kithforest", fullName = "Kithicor Forest", zem = { emu = 1.00, live = "--" }, levelMin = 10, levelMax = 25, expansion = "Classic", isHotzone = false, isCity = false},
        {shortName = "kithicor", fullName = "Kithicor Woods", zem = { emu = 1.00, live = "--" }, levelMin = 10, levelMax = 25, expansion = "Classic", isHotzone = false, isCity = false},
        {shortName = "kodtaz", fullName = "Kod'Taz, Broken Trial Grounds", zem = { emu = 2.50, live = "--" }, levelMin = 60, levelMax = 70, expansion = "GoD", isHotzone = true, isCity = false},
        {shortName = "korascian", fullName = "Korascian Warrens", zem = { emu = 1.50, live = "--" }, levelMin = 75, levelMax = 85, expansion = "SoF", isHotzone = true, isCity = false},
        {shortName = "kurn", fullName = "Kurn's Tower", zem = { emu = 2.00, live = "--" }, levelMin = 10, levelMax = 25, expansion = "RoK", isHotzone = true, isCity = false},
        {shortName = "lakeofillomen", fullName = "Lake of Ill Omen", zem = { emu = 0.80, live = "--" }, levelMin = 1, levelMax = 20, expansion = "RoK", isHotzone = false, isCity = false},
        {shortName = "lakerathe", fullName = "Lake Rathetear", zem = { emu = 1.00, live = "--" }, levelMin = 15, levelMax = 30, expansion = "Classic", isHotzone = false, isCity = false},
        {shortName = "lavastorm", fullName = "Lavastorm Mountains", zem = { emu = 0.75, live = "--" }, levelMin = 10, levelMax = 25, expansion = "Classic", isHotzone = false, isCity = false},
        {shortName = "letalis", fullName = "Mons Letalis", zem = { emu = 1.75, live = "--" }, levelMin = 35, levelMax = 50, expansion = "Luclin", isHotzone = true, isCity = false},
        {shortName = "lfaydark", fullName = "Lesser Faydark", zem = { emu = 1.00, live = "--" }, levelMin = 10, levelMax = 25, expansion = "Classic", isHotzone = false, isCity = false},
        {shortName = "load", fullName = "Loading Zone", zem = { emu = 1.00, live = "--" }, levelMin = 1, levelMax = 100, expansion = "Live", isHotzone = false, isCity = false},
        {shortName = "load2", fullName = "Loading Zone 2", zem = { emu = 1.00, live = "--" }, levelMin = 1, levelMax = 100, expansion = "Live", isHotzone = false, isCity = false},
        {shortName = "lopingplains", fullName = "Loping Plains", zem = { emu = 1.00, live = "--" }, levelMin = 75, levelMax = 85, expansion = "SoF", isHotzone = false, isCity = false},
        {shortName = "maiden", fullName = "Maiden's Eye", zem = { emu = 1.00, live = "--" }, levelMin = 35, levelMax = 50, expansion = "Luclin", isHotzone = false, isCity = false},
        {shortName = "maidensgrave", fullName = "Maiden's Grave", zem = { emu = 1.00, live = "--" }, levelMin = 60, levelMax = 75, expansion = "TBS", isHotzone = false, isCity = false},
        {shortName = "mansion", fullName = "Mansion of the Mind", zem = { emu = 1.00, live = "--" }, levelMin = 75, levelMax = 85, expansion = "SoF", isHotzone = false, isCity = false},
        {shortName = "mechanotus", fullName = "Fortress Mechanotus", zem = { emu = 1.00, live = "--" }, levelMin = 75, levelMax = 85, expansion = "SoF", isHotzone = false, isCity = false},
        {shortName = "mesa", fullName = "Gorowyn Mesa", zem = { emu = 1.00, live = "--" }, levelMin = 75, levelMax = 85, expansion = "SoF", isHotzone = false, isCity = false},
        {shortName = "mira", fullName = "Mines of Nurga A", zem = { emu = 1.50, live = "--" }, levelMin = 35, levelMax = 50, expansion = "RoK", isHotzone = true, isCity = false},
        {shortName = "mirb", fullName = "Mines of Nurga B", zem = { emu = 1.50, live = "--" }, levelMin = 35, levelMax = 50, expansion = "RoK", isHotzone = true, isCity = false},
        {shortName = "mirc", fullName = "Mines of Nurga C", zem = { emu = 1.50, live = "--" }, levelMin = 35, levelMax = 50, expansion = "RoK", isHotzone = true, isCity = false},
        {shortName = "mird", fullName = "Mines of Nurga D", zem = { emu = 1.50, live = "--" }, levelMin = 35, levelMax = 50, expansion = "RoK", isHotzone = true, isCity = false},
        {shortName = "mire", fullName = "Mines of Nurga E", zem = { emu = 1.50, live = "--" }, levelMin = 35, levelMax = 50, expansion = "RoK", isHotzone = true, isCity = false},
        {shortName = "mirf", fullName = "Mines of Nurga F", zem = { emu = 1.50, live = "--" }, levelMin = 35, levelMax = 50, expansion = "RoK", isHotzone = true, isCity = false},
        {shortName = "mirg", fullName = "Mines of Nurga G", zem = { emu = 1.50, live = "--" }, levelMin = 35, levelMax = 50, expansion = "RoK", isHotzone = true, isCity = false},
        {shortName = "mirh", fullName = "Mines of Nurga H", zem = { emu = 1.50, live = "--" }, levelMin = 35, levelMax = 50, expansion = "RoK", isHotzone = true, isCity = false},
        {shortName = "miri", fullName = "Mines of Nurga I", zem = { emu = 1.50, live = "--" }, levelMin = 35, levelMax = 50, expansion = "RoK", isHotzone = true, isCity = false},
        {shortName = "mirj", fullName = "Mines of Nurga J", zem = { emu = 1.50, live = "--" }, levelMin = 35, levelMax = 50, expansion = "RoK", isHotzone = true, isCity = false},
        {shortName = "mischiefplane", fullName = "Plane of Mischief", zem = { emu = 1.13, live = "--" }, levelMin = 45, levelMax = 60, expansion = "Velious", isHotzone = false, isCity = false},
        {shortName = "mistmoore", fullName = "Castle Mistmoore", zem = { emu = 1.20, live = "--" }, levelMin = 20, levelMax = 40, expansion = "Classic", isHotzone = true, isCity = false},
        {shortName = "misty", fullName = "Misty Thicket", zem = { emu = 1.00, live = "--" }, levelMin = 1, levelMax = 15, expansion = "Classic", isHotzone = false, isCity = false},
        {shortName = "mistythicket", fullName = "Misty Thicket", zem = { emu = 1.00, live = "--" }, levelMin = 1, levelMax = 15, expansion = "Classic", isHotzone = false, isCity = false},
        {shortName = "mmca", fullName = "Mistmoore Catacombs A", zem = { emu = 1.50, live = "--" }, levelMin = 65, levelMax = 75, expansion = "LoY", isHotzone = true, isCity = false},
        {shortName = "mmcb", fullName = "Mistmoore Catacombs B", zem = { emu = 1.50, live = "--" }, levelMin = 65, levelMax = 75, expansion = "LoY", isHotzone = true, isCity = false},
        {shortName = "mmcc", fullName = "Mistmoore Catacombs C", zem = { emu = 1.50, live = "--" }, levelMin = 65, levelMax = 75, expansion = "LoY", isHotzone = true, isCity = false},
        {shortName = "mmcd", fullName = "Mistmoore Catacombs D", zem = { emu = 1.50, live = "--" }, levelMin = 65, levelMax = 75, expansion = "LoY", isHotzone = true, isCity = false},
        {shortName = "mmce", fullName = "Mistmoore Catacombs E", zem = { emu = 1.50, live = "--" }, levelMin = 65, levelMax = 75, expansion = "LoY", isHotzone = true, isCity = false},
        {shortName = "mmcf", fullName = "Mistmoore Catacombs F", zem = { emu = 1.50, live = "--" }, levelMin = 65, levelMax = 75, expansion = "LoY", isHotzone = true, isCity = false},
        {shortName = "mmcg", fullName = "Mistmoore Catacombs G", zem = { emu = 1.50, live = "--" }, levelMin = 65, levelMax = 75, expansion = "LoY", isHotzone = true, isCity = false},
        {shortName = "mmch", fullName = "Mistmoore Catacombs H", zem = { emu = 1.50, live = "--" }, levelMin = 65, levelMax = 75, expansion = "LoY", isHotzone = true, isCity = false},
        {shortName = "mmci", fullName = "Mistmoore Catacombs I", zem = { emu = 1.50, live = "--" }, levelMin = 65, levelMax = 75, expansion = "LoY", isHotzone = true, isCity = false},
        {shortName = "mmcj", fullName = "Mistmoore Catacombs J", zem = { emu = 1.50, live = "--" }, levelMin = 65, levelMax = 75, expansion = "LoY", isHotzone = true, isCity = false},
        {shortName = "monkeyrock", fullName = "Monkey Rock", zem = { emu = 1.00, live = "--" }, levelMin = 60, levelMax = 75, expansion = "TBS", isHotzone = false, isCity = false},
        {shortName = "moors", fullName = "Blightfire Moors", zem = { emu = 1.00, live = "--" }, levelMin = 15, levelMax = 35, expansion = "TSS", isHotzone = false, isCity = false},
        {shortName = "mseru", fullName = "Marus Seru", zem = { emu = 1.00, live = "--" }, levelMin = 25, levelMax = 45, expansion = "Luclin", isHotzone = false, isCity = false},
        {shortName = "nadox", fullName = "Crypt of Nadox", zem = { emu = 1.50, live = "--" }, levelMin = 40, levelMax = 55, expansion = "Luclin", isHotzone = true, isCity = false},
        {shortName = "najena", fullName = "Najena", zem = { emu = 1.73, live = "--" }, levelMin = 15, levelMax = 35, expansion = "Classic", isHotzone = true, isCity = false},
        {shortName = "natimbi", fullName = "Natimbi, The Broken Shores", zem = { emu = 1.50, live = "--" }, levelMin = 40, levelMax = 60, expansion = "GoD", isHotzone = true, isCity = false},
        {shortName = "necropolis", fullName = "Dragon Necropolis", zem = { emu = 1.50, live = "--" }, levelMin = 45, levelMax = 60, expansion = "Velious", isHotzone = true, isCity = false},
        {shortName = "nedaria", fullName = "Nedaria's Landing", zem = { emu = 1.00, live = "--" }, levelMin = 15, levelMax = 35, expansion = "LoY", isHotzone = false, isCity = true},
        {shortName = "nektulos", fullName = "Nektulos Forest", zem = { emu = 1.00, live = "--" }, levelMin = 1, levelMax = 20, expansion = "Classic", isHotzone = false, isCity = false},
        {shortName = "nektulosa", fullName = "Nektulos Depths", zem = { emu = 1.00, live = "--" }, levelMin = 1, levelMax = 20, expansion = "Classic", isHotzone = false, isCity = false},
        {shortName = "neriaka", fullName = "Neriak Commons", zem = { emu = 1.33, live = "--" }, levelMin = 1, levelMax = 20, expansion = "Classic", isHotzone = false, isCity = true},
        {shortName = "neriakb", fullName = "Neriak Foreign Quarter", zem = { emu = 1.33, live = "--" }, levelMin = 1, levelMax = 20, expansion = "Classic", isHotzone = false, isCity = true},
        {shortName = "neriakc", fullName = "Neriak Third Gate", zem = { emu = 1.33, live = "--" }, levelMin = 1, levelMax = 20, expansion = "Classic", isHotzone = false, isCity = true},
        {shortName = "neriakd", fullName = "Neriak Fourth Gate", zem = { emu = 1.00, live = "--" }, levelMin = 1, levelMax = 20, expansion = "Classic", isHotzone = false, isCity = true},
        {shortName = "netherbian", fullName = "Netherbian Lair", zem = { emu = 1.06, live = "--" }, levelMin = 25, levelMax = 40, expansion = "Luclin", isHotzone = false, isCity = false},
        {shortName = "nexus", fullName = "Nexus", zem = { emu = 1.00, live = "--" }, levelMin = 1, levelMax = 100, expansion = "Luclin", isHotzone = false, isCity = true},
        {shortName = "nightmareb", fullName = "Lair of Terris Thule", zem = { emu = 2.35, live = "--" }, levelMin = 55, levelMax = 65, expansion = "PoP", isHotzone = true, isCity = false},
        {shortName = "northkarana", fullName = "North Karana", zem = { emu = 1.00, live = "--" }, levelMin = 10, levelMax = 25, expansion = "Classic", isHotzone = false, isCity = false},
        {shortName = "northro", fullName = "North Ro", zem = { emu = 1.00, live = "--" }, levelMin = 1, levelMax = 15, expansion = "Classic", isHotzone = false, isCity = false},
        {shortName = "nro", fullName = "North Ro", zem = { emu = 1.00, live = "--" }, levelMin = 1, levelMax = 15, expansion = "Classic", isHotzone = false, isCity = false},
        {shortName = "nurga", fullName = "Mines of Nurga", zem = { emu = 0.95, live = "--" }, levelMin = 35, levelMax = 50, expansion = "RoK", isHotzone = false, isCity = false},
        {shortName = "oasis", fullName = "Oasis of Marr", zem = { emu = 1.00, live = "--" }, levelMin = 10, levelMax = 25, expansion = "Classic", isHotzone = false, isCity = false},
        {shortName = "oceangreenhills", fullName = "Oceangreen Hills", zem = { emu = 1.50, live = "--" }, levelMin = 70, levelMax = 80, expansion = "SoF", isHotzone = true, isCity = false},
        {shortName = "oceangreenvillage", fullName = "Oceangreen Village", zem = { emu = 1.50, live = "--" }, levelMin = 70, levelMax = 80, expansion = "SoF", isHotzone = true, isCity = false},
        {shortName = "oceanoftears", fullName = "Ocean of Tears", zem = { emu = 1.00, live = "--" }, levelMin = 10, levelMax = 25, expansion = "Classic", isHotzone = false, isCity = false},
        {shortName = "oggok", fullName = "Oggok", zem = { emu = 1.33, live = "--" }, levelMin = 1, levelMax = 20, expansion = "Classic", isHotzone = false, isCity = true},
        {shortName = "oldblackburrow", fullName = "Old Blackburrow", zem = { emu = 1.50, live = "--" }, levelMin = 70, levelMax = 80, expansion = "SoF", isHotzone = true, isCity = false},
        {shortName = "oldbloodfield", fullName = "Old Bloodfields", zem = { emu = 1.50, live = "--" }, levelMin = 70, levelMax = 80, expansion = "SoF", isHotzone = true, isCity = false},
        {shortName = "oldcommons", fullName = "Old Commonlands", zem = { emu = 1.50, live = "--" }, levelMin = 70, levelMax = 80, expansion = "SoF", isHotzone = true, isCity = false},
        {shortName = "olddranik", fullName = "Old Dranik's Scar", zem = { emu = 1.50, live = "--" }, levelMin = 70, levelMax = 80, expansion = "SoF", isHotzone = true, isCity = false},
        {shortName = "oldfieldofbone", fullName = "Old Field of Bone", zem = { emu = 1.50, live = "--" }, levelMin = 70, levelMax = 80, expansion = "SoF", isHotzone = true, isCity = false},
        {shortName = "oldhighpass", fullName = "Old Highpass Hold", zem = { emu = 1.50, live = "--" }, levelMin = 70, levelMax = 80, expansion = "SoF", isHotzone = true, isCity = false},
        {shortName = "oldkaesoraa", fullName = "Old Kaesora A", zem = { emu = 1.50, live = "--" }, levelMin = 70, levelMax = 80, expansion = "SoF", isHotzone = true, isCity = false},
        {shortName = "oldkaesorab", fullName = "Old Kaesora B", zem = { emu = 1.50, live = "--" }, levelMin = 70, levelMax = 80, expansion = "SoF", isHotzone = true, isCity = false},
        {shortName = "oldkithicor", fullName = "Old Kithicor", zem = { emu = 1.50, live = "--" }, levelMin = 70, levelMax = 80, expansion = "SoF", isHotzone = true, isCity = false},
        {shortName = "oldkurn", fullName = "Old Kurn's Tower", zem = { emu = 1.50, live = "--" }, levelMin = 70, levelMax = 80, expansion = "SoF", isHotzone = true, isCity = false},
        {shortName = "oot", fullName = "Ocean of Tears", zem = { emu = 1.13, live = "--" }, levelMin = 10, levelMax = 25, expansion = "Classic", isHotzone = false, isCity = false},
        {shortName = "overthere", fullName = "The Overthere", zem = { emu = 1.00, live = "--" }, levelMin = 15, levelMax = 35, expansion = "RoK", isHotzone = false, isCity = false},
        {shortName = "paineel", fullName = "Paineel", zem = { emu = 1.00, live = "--" }, levelMin = 1, levelMax = 20, expansion = "Classic", isHotzone = false, isCity = true},
        {shortName = "paludal", fullName = "Paludal Caverns", zem = { emu = 1.75, live = "--" }, levelMin = 15, levelMax = 35, expansion = "Luclin", isHotzone = true, isCity = false},
        {shortName = "paw", fullName = "Lair of the Splitpaw", zem = { emu = 0.90, live = "--" }, levelMin = 15, levelMax = 35, expansion = "Classic", isHotzone = false, isCity = false},
        {shortName = "permafrost", fullName = "Permafrost Keep", zem = { emu = 1.20, live = "--" }, levelMin = 25, levelMax = 45, expansion = "Classic", isHotzone = true, isCity = false},
        {shortName = "poair", fullName = "Plane of Air", zem = { emu = 2.75, live = "--" }, levelMin = 60, levelMax = 70, expansion = "PoP", isHotzone = true, isCity = false},
        {shortName = "podisease", fullName = "Plane of Disease", zem = { emu = 1.58, live = "--" }, levelMin = 55, levelMax = 65, expansion = "PoP", isHotzone = true, isCity = false},
        {shortName = "poeartha", fullName = "Plane of Earth A", zem = { emu = 3.00, live = "--" }, levelMin = 60, levelMax = 70, expansion = "PoP", isHotzone = true, isCity = false},
        {shortName = "poearthb", fullName = "Plane of Earth B", zem = { emu = 3.00, live = "--" }, levelMin = 60, levelMax = 70, expansion = "PoP", isHotzone = true, isCity = false},
        {shortName = "pofire", fullName = "Plane of Fire", zem = { emu = 3.00, live = "--" }, levelMin = 60, levelMax = 70, expansion = "PoP", isHotzone = true, isCity = false},
        {shortName = "poinnovation", fullName = "Plane of Innovation", zem = { emu = 1.58, live = "--" }, levelMin = 55, levelMax = 65, expansion = "PoP", isHotzone = true, isCity = false},
        {shortName = "pojustice", fullName = "Plane of Justice", zem = { emu = 1.58, live = "--" }, levelMin = 55, levelMax = 65, expansion = "PoP", isHotzone = true, isCity = false},
        {shortName = "poknowledge", fullName = "Plane of Knowledge", zem = { emu = 1.00, live = "--" }, levelMin = 1, levelMax = 100, expansion = "PoP", isHotzone = false, isCity = true},
        {shortName = "ponightmare", fullName = "Plane of Nightmare", zem = { emu = 1.58, live = "--" }, levelMin = 55, levelMax = 65, expansion = "PoP", isHotzone = true, isCity = false},
        {shortName = "postorms", fullName = "Plane of Storms", zem = { emu = 2.35, live = "--" }, levelMin = 55, levelMax = 65, expansion = "PoP", isHotzone = true, isCity = false},
        {shortName = "potactics", fullName = "Drunder, Fortress of Zek", zem = { emu = 2.75, live = "--" }, levelMin = 60, levelMax = 70, expansion = "PoP", isHotzone = true, isCity = false},
        {shortName = "potimea", fullName = "Plane of Time A", zem = { emu = 0.40, live = "--" }, levelMin = 60, levelMax = 70, expansion = "PoP", isHotzone = false, isCity = false},
        {shortName = "potimeb", fullName = "Plane of Time B", zem = { emu = 2.75, live = "--" }, levelMin = 60, levelMax = 70, expansion = "PoP", isHotzone = true, isCity = false},
        {shortName = "potorment", fullName = "Plane of Torment", zem = { emu = 2.75, live = "--" }, levelMin = 60, levelMax = 70, expansion = "PoP", isHotzone = true, isCity = false},
        {shortName = "potranquility", fullName = "Plane of Tranquility", zem = { emu = 1.00, live = "--" }, levelMin = 1, levelMax = 100, expansion = "PoP", isHotzone = false, isCity = true},
        {shortName = "povalor", fullName = "Plane of Valor", zem = { emu = 2.35, live = "--" }, levelMin = 55, levelMax = 65, expansion = "PoP", isHotzone = true, isCity = false},
        {shortName = "powar", fullName = "Plane of War", zem = { emu = 1.00, live = "--" }, levelMin = 95, levelMax = 110, expansion = "RoF", isHotzone = false, isCity = false},
        {shortName = "powater", fullName = "Plane of Water", zem = { emu = 3.00, live = "--" }, levelMin = 60, levelMax = 70, expansion = "PoP", isHotzone = true, isCity = false},
        {shortName = "precipiceofwar", fullName = "Precipice of War", zem = { emu = 1.50, live = "--" }, levelMin = 70, levelMax = 80, expansion = "SoF", isHotzone = true, isCity = false},
        {shortName = "provinggrounds", fullName = "Muramite Proving Grounds", zem = { emu = 2.75, live = "--" }, levelMin = 65, levelMax = 75, expansion = "OoW", isHotzone = true, isCity = false},
        {shortName = "qcat", fullName = "Qeynos Catacombs", zem = { emu = 1.00, live = "--" }, levelMin = 5, levelMax = 20, expansion = "Classic", isHotzone = false, isCity = false},
        {shortName = "qey2hh1", fullName = "Surefall Glade", zem = { emu = 1.00, live = "--" }, levelMin = 1, levelMax = 15, expansion = "Classic", isHotzone = false, isCity = false},
        {shortName = "qeynos", fullName = "South Qeynos", zem = { emu = 1.00, live = "--" }, levelMin = 1, levelMax = 20, expansion = "Classic", isHotzone = false, isCity = true},
        {shortName = "qeynos2", fullName = "North Qeynos", zem = { emu = 1.00, live = "--" }, levelMin = 1, levelMax = 20, expansion = "Classic", isHotzone = false, isCity = true},
        {shortName = "qeytoqrg", fullName = "Qeynos Hills", zem = { emu = 1.00, live = "--" }, levelMin = 1, levelMax = 15, expansion = "Classic", isHotzone = false, isCity = false},
        {shortName = "qinimi", fullName = "Qinimi, Court of Nihilia", zem = { emu = 2.00, live = "--" }, levelMin = 60, levelMax = 70, expansion = "GoD", isHotzone = true, isCity = false},
        {shortName = "qrg", fullName = "Surefall Glade", zem = { emu = 1.33, live = "--" }, levelMin = 1, levelMax = 15, expansion = "Classic", isHotzone = false, isCity = true},
        {shortName = "qvic", fullName = "Qvic, Prayer Grounds of Calling", zem = { emu = 2.00, live = "--" }, levelMin = 60, levelMax = 70, expansion = "GoD", isHotzone = true, isCity = false},
        {shortName = "qvicb", fullName = "Qvic Depths", zem = { emu = 1.00, live = "--" }, levelMin = 60, levelMax = 70, expansion = "GoD", isHotzone = false, isCity = false},
        {shortName = "rage", fullName = "Rage, Domain of Anger", zem = { emu = 1.00, live = "--" }, levelMin = 65, levelMax = 75, expansion = "PoR", isHotzone = false, isCity = false},
        {shortName = "ragea", fullName = "Rage Annex", zem = { emu = 1.00, live = "--" }, levelMin = 65, levelMax = 75, expansion = "PoR", isHotzone = false, isCity = false},
        {shortName = "rathechamber", fullName = "Rathe Council Chamber", zem = { emu = 1.50, live = "--" }, levelMin = 70, levelMax = 80, expansion = "SoF", isHotzone = true, isCity = false},
        {shortName = "rathemtn", fullName = "Rathe Mountains", zem = { emu = 1.00, live = "--" }, levelMin = 10, levelMax = 25, expansion = "Classic", isHotzone = false, isCity = false},
        {shortName = "redfeather", fullName = "Redfeather Isle", zem = { emu = 1.00, live = "--" }, levelMin = 60, levelMax = 75, expansion = "TBS", isHotzone = false, isCity = false},
        {shortName = "relic", fullName = "Relic, the Artifact City", zem = { emu = 1.00, live = "--" }, levelMin = 65, levelMax = 75, expansion = "PoR", isHotzone = false, isCity = false},
        {shortName = "riftseekers", fullName = "Riftseekers' Sanctum", zem = { emu = 3.00, live = "--" }, levelMin = 65, levelMax = 75, expansion = "OoW", isHotzone = true, isCity = false},
        {shortName = "rivervale", fullName = "Rivervale", zem = { emu = 1.33, live = "--" }, levelMin = 1, levelMax = 20, expansion = "Classic", isHotzone = false, isCity = true},
        {shortName = "riwwi", fullName = "Riwwi, Coliseum of Games", zem = { emu = 2.00, live = "--" }, levelMin = 60, levelMax = 70, expansion = "GoD", isHotzone = true, isCity = false},
        {shortName = "roost", fullName = "Blackfeather Roost", zem = { emu = 1.00, live = "--" }, levelMin = 60, levelMax = 75, expansion = "TBS", isHotzone = false, isCity = false},
        {shortName = "ruja", fullName = "Ruins of Takish-Hiz A", zem = { emu = 1.50, live = "--" }, levelMin = 65, levelMax = 75, expansion = "DoDh", isHotzone = true, isCity = false},
        {shortName = "rujb", fullName = "Ruins of Takish-Hiz B", zem = { emu = 1.50, live = "--" }, levelMin = 65, levelMax = 75, expansion = "DoDh", isHotzone = true, isCity = false},
        {shortName = "rujc", fullName = "Ruins of Takish-Hiz C", zem = { emu = 1.50, live = "--" }, levelMin = 65, levelMax = 75, expansion = "DoDh", isHotzone = true, isCity = false},
        {shortName = "rujd", fullName = "Ruins of Takish-Hiz D", zem = { emu = 1.50, live = "--" }, levelMin = 65, levelMax = 75, expansion = "DoDh", isHotzone = true, isCity = false},
        {shortName = "ruje", fullName = "Ruins of Takish-Hiz E", zem = { emu = 1.50, live = "--" }, levelMin = 65, levelMax = 75, expansion = "DoDh", isHotzone = true, isCity = false},
        {shortName = "rujf", fullName = "Ruins of Takish-Hiz F", zem = { emu = 1.50, live = "--" }, levelMin = 65, levelMax = 75, expansion = "DoDh", isHotzone = true, isCity = false},
        {shortName = "rujg", fullName = "Ruins of Takish-Hiz G", zem = { emu = 1.50, live = "--" }, levelMin = 65, levelMax = 75, expansion = "DoDh", isHotzone = true, isCity = false},
        {shortName = "rujh", fullName = "Ruins of Takish-Hiz H", zem = { emu = 1.50, live = "--" }, levelMin = 65, levelMax = 75, expansion = "DoDh", isHotzone = true, isCity = false},
        {shortName = "ruji", fullName = "Ruins of Takish-Hiz I", zem = { emu = 1.50, live = "--" }, levelMin = 65, levelMax = 75, expansion = "DoDh", isHotzone = true, isCity = false},
        {shortName = "rujj", fullName = "Ruins of Takish-Hiz J", zem = { emu = 1.50, live = "--" }, levelMin = 65, levelMax = 75, expansion = "DoDh", isHotzone = true, isCity = false},
        {shortName = "runnyeye", fullName = "Runnyeye Citadel", zem = { emu = 1.33, live = "--" }, levelMin = 10, levelMax = 30, expansion = "Classic", isHotzone = true, isCity = false},
        {shortName = "scarlet", fullName = "Scarlet Desert", zem = { emu = 1.00, live = "--" }, levelMin = 35, levelMax = 50, expansion = "Luclin", isHotzone = false, isCity = false},
        {shortName = "sebilis", fullName = "Old Sebilis", zem = { emu = 2.50, live = "--" }, levelMin = 45, levelMax = 60, expansion = "RoK", isHotzone = true, isCity = false},
        {shortName = "shadeweaver", fullName = "Shadeweaver's Thicket", zem = { emu = 1.00, live = "--" }, levelMin = 15, levelMax = 35, expansion = "Luclin", isHotzone = false, isCity = false},
        {shortName = "shadowhaven", fullName = "Shadow Haven", zem = { emu = 1.33, live = "--" }, levelMin = 1, levelMax = 100, expansion = "Luclin", isHotzone = false, isCity = true},
        {shortName = "shadowrest", fullName = "Shadowrest", zem = { emu = 1.00, live = "--" }, levelMin = 1, levelMax = 100, expansion = "LoY", isHotzone = false, isCity = true},
        {shortName = "shadowspine", fullName = "Shadowspine", zem = { emu = 1.00, live = "--" }, levelMin = 65, levelMax = 75, expansion = "DoDh", isHotzone = false, isCity = false},
        {shortName = "sharvahl", fullName = "Shar Vahl", zem = { emu = 1.00, live = "--" }, levelMin = 1, levelMax = 20, expansion = "Luclin", isHotzone = false, isCity = true},
        {shortName = "shipmvm", fullName = "Ship: Maiden's Voyage Merchant", zem = { emu = 1.00, live = "--" }, levelMin = 60, levelMax = 75, expansion = "TBS", isHotzone = false, isCity = false},
        {shortName = "shipmvp", fullName = "Ship: Maiden's Voyage Pirate", zem = { emu = 1.00, live = "--" }, levelMin = 60, levelMax = 75, expansion = "TBS", isHotzone = false, isCity = false},
        {shortName = "shipmvu", fullName = "Ship: Maiden's Voyage Upper", zem = { emu = 1.00, live = "--" }, levelMin = 60, levelMax = 75, expansion = "TBS", isHotzone = false, isCity = false},
        {shortName = "shippvu", fullName = "Ship: Pirate Vessel Upper", zem = { emu = 1.00, live = "--" }, levelMin = 60, levelMax = 75, expansion = "TBS", isHotzone = false, isCity = false},
        {shortName = "shipuvu", fullName = "Ship: Undead Vessel Upper", zem = { emu = 1.00, live = "--" }, levelMin = 60, levelMax = 75, expansion = "TBS", isHotzone = false, isCity = false},
        {shortName = "shipworkshop", fullName = "Ship Workshop", zem = { emu = 1.00, live = "--" }, levelMin = 75, levelMax = 85, expansion = "SoF", isHotzone = false, isCity = false},
        {shortName = "silyssar", fullName = "Silyssar, New Chelsith", zem = { emu = 1.00, live = "--" }, levelMin = 75, levelMax = 85, expansion = "TBS", isHotzone = false, isCity = false},
        {shortName = "sirens", fullName = "Siren's Grotto", zem = { emu = 0.85, live = "--" }, levelMin = 45, levelMax = 60, expansion = "Velious", isHotzone = false, isCity = false},
        {shortName = "skyfire", fullName = "Skyfire Mountains", zem = { emu = 1.06, live = "--" }, levelMin = 40, levelMax = 55, expansion = "RoK", isHotzone = false, isCity = false},
        {shortName = "skylance", fullName = "Skylance", zem = { emu = 1.00, live = "--" }, levelMin = 65, levelMax = 75, expansion = "PoR", isHotzone = false, isCity = false},
        {shortName = "skyshrine", fullName = "Skyshrine", zem = { emu = 1.13, live = "--" }, levelMin = 35, levelMax = 60, expansion = "Velious", isHotzone = false, isCity = true},
        {shortName = "sleeper", fullName = "Sleeper's Tomb", zem = { emu = 1.20, live = "--" }, levelMin = 50, levelMax = 60, expansion = "Velious", isHotzone = true, isCity = false},
        {shortName = "sncrematory", fullName = "Sewers of Nihilia, Crematory", zem = { emu = 1.50, live = "--" }, levelMin = 60, levelMax = 70, expansion = "GoD", isHotzone = true, isCity = false},
        {shortName = "snlair", fullName = "Sewers of Nihilia, Lair of Trapped Ones", zem = { emu = 1.50, live = "--" }, levelMin = 60, levelMax = 70, expansion = "GoD", isHotzone = true, isCity = false},
        {shortName = "snplant", fullName = "Sewers of Nihilia, Purifying Plant", zem = { emu = 1.50, live = "--" }, levelMin = 60, levelMax = 70, expansion = "GoD", isHotzone = true, isCity = false},
        {shortName = "snpool", fullName = "Sewers of Nihilia, Pool of Sludge", zem = { emu = 1.50, live = "--" }, levelMin = 60, levelMax = 70, expansion = "GoD", isHotzone = true, isCity = false},
        {shortName = "soldunga", fullName = "Solusek's Eye", zem = { emu = 1.73, live = "--" }, levelMin = 25, levelMax = 45, expansion = "Classic", isHotzone = true, isCity = false},
        {shortName = "soldungb", fullName = "Nagafen's Lair", zem = { emu = 1.06, live = "--" }, levelMin = 40, levelMax = 55, expansion = "Classic", isHotzone = false, isCity = false},
        {shortName = "soldungc", fullName = "Solusek C", zem = { emu = 2.00, live = "--" }, levelMin = 65, levelMax = 75, expansion = "OoW", isHotzone = true, isCity = false},
        {shortName = "solrotower", fullName = "Tower of Solusek Ro", zem = { emu = 2.75, live = "--" }, levelMin = 55, levelMax = 65, expansion = "PoP", isHotzone = true, isCity = false},
        {shortName = "soltemple", fullName = "Temple of Solusek Ro", zem = { emu = 1.33, live = "--" }, levelMin = 15, levelMax = 35, expansion = "Classic", isHotzone = true, isCity = false},
        {shortName = "solteris", fullName = "Solteris, the Throne of Ro", zem = { emu = 1.00, live = "--" }, levelMin = 75, levelMax = 85, expansion = "TBS", isHotzone = false, isCity = false},
        {shortName = "southkarana", fullName = "South Karana", zem = { emu = 1.00, live = "--" }, levelMin = 15, levelMax = 35, expansion = "Classic", isHotzone = false, isCity = false},
        {shortName = "southro", fullName = "South Ro", zem = { emu = 1.00, live = "--" }, levelMin = 1, levelMax = 15, expansion = "Classic", isHotzone = false, isCity = false},
        {shortName = "sro", fullName = "South Ro", zem = { emu = 1.00, live = "--" }, levelMin = 1, levelMax = 15, expansion = "Classic", isHotzone = false, isCity = false},
        {shortName = "sseru", fullName = "Sanctus Seru", zem = { emu = 1.13, live = "--" }, levelMin = 35, levelMax = 55, expansion = "Luclin", isHotzone = false, isCity = true},
        {shortName = "ssratemple", fullName = "Ssraeshza Temple", zem = { emu = 1.33, live = "--" }, levelMin = 55, levelMax = 65, expansion = "Luclin", isHotzone = true, isCity = false},
        {shortName = "steamfactory", fullName = "Steam Factory", zem = { emu = 1.00, live = "--" }, levelMin = 75, levelMax = 85, expansion = "SoF", isHotzone = false, isCity = false},
        {shortName = "steamfont", fullName = "Steamfont Mountains", zem = { emu = 1.00, live = "--" }, levelMin = 1, levelMax = 20, expansion = "Classic", isHotzone = false, isCity = false},
        {shortName = "steamfontmts", fullName = "Steamfont Mountains", zem = { emu = 1.00, live = "--" }, levelMin = 1, levelMax = 20, expansion = "Classic", isHotzone = false, isCity = false},
        {shortName = "steppes", fullName = "The Steppes", zem = { emu = 1.00, live = "--" }, levelMin = 60, levelMax = 75, expansion = "TBS", isHotzone = false, isCity = false},
        {shortName = "stillmoona", fullName = "Stillmoon Temple", zem = { emu = 3.00, live = "--" }, levelMin = 60, levelMax = 70, expansion = "DoN", isHotzone = true, isCity = false},
        {shortName = "stillmoonb", fullName = "Stillmoon Temple: Inner Sanctum", zem = { emu = 3.00, live = "--" }, levelMin = 60, levelMax = 70, expansion = "DoN", isHotzone = true, isCity = false},
        {shortName = "stonebrunt", fullName = "Stonebrunt Mountains", zem = { emu = 1.00, live = "--" }, levelMin = 15, levelMax = 35, expansion = "Classic", isHotzone = false, isCity = false},
        {shortName = "stonehive", fullName = "Stone Hive", zem = { emu = 1.00, live = "--" }, levelMin = 60, levelMax = 75, expansion = "TSS", isHotzone = false, isCity = false},
        {shortName = "suncrest", fullName = "Suncrest Isle", zem = { emu = 1.00, live = "--" }, levelMin = 60, levelMax = 75, expansion = "TBS", isHotzone = false, isCity = false},
        {shortName = "sunderock", fullName = "Sunderock Springs", zem = { emu = 1.00, live = "--" }, levelMin = 60, levelMax = 75, expansion = "TSS", isHotzone = false, isCity = false},
        {shortName = "swampofnohope", fullName = "Swamp of No Hope", zem = { emu = 1.00, live = "--" }, levelMin = 10, levelMax = 25, expansion = "RoK", isHotzone = false, isCity = false},
        {shortName = "tacvi", fullName = "Tacvi, Seat of the Slaver", zem = { emu = 1.00, live = "--" }, levelMin = 65, levelMax = 75, expansion = "GoD", isHotzone = false, isCity = false},
        {shortName = "takb", fullName = "Takish-Hiz B", zem = { emu = 1.50, live = "--" }, levelMin = 65, levelMax = 75, expansion = "DoDh", isHotzone = true, isCity = false},
        {shortName = "takc", fullName = "Takish-Hiz C", zem = { emu = 1.50, live = "--" }, levelMin = 65, levelMax = 75, expansion = "DoDh", isHotzone = true, isCity = false},
        {shortName = "takd", fullName = "Takish-Hiz D", zem = { emu = 1.50, live = "--" }, levelMin = 65, levelMax = 75, expansion = "DoDh", isHotzone = true, isCity = false},
        {shortName = "take", fullName = "Takish-Hiz E", zem = { emu = 1.50, live = "--" }, levelMin = 65, levelMax = 75, expansion = "DoDh", isHotzone = true, isCity = false},
        {shortName = "takf", fullName = "Takish-Hiz F", zem = { emu = 1.50, live = "--" }, levelMin = 65, levelMax = 75, expansion = "DoDh", isHotzone = true, isCity = false},
        {shortName = "takg", fullName = "Takish-Hiz G", zem = { emu = 1.50, live = "--" }, levelMin = 65, levelMax = 75, expansion = "DoDh", isHotzone = true, isCity = false},
        {shortName = "takh", fullName = "Takish-Hiz H", zem = { emu = 1.50, live = "--" }, levelMin = 65, levelMax = 75, expansion = "DoDh", isHotzone = true, isCity = false},
        {shortName = "taki", fullName = "Takish-Hiz I", zem = { emu = 1.50, live = "--" }, levelMin = 65, levelMax = 75, expansion = "DoDh", isHotzone = true, isCity = false},
        {shortName = "takishruins", fullName = "Ruins of Takish-Hiz", zem = { emu = 1.00, live = "--" }, levelMin = 65, levelMax = 75, expansion = "DoDh", isHotzone = false, isCity = false},
        {shortName = "takishruinsa", fullName = "Ruins of Takish-Hiz A", zem = { emu = 1.00, live = "--" }, levelMin = 65, levelMax = 75, expansion = "DoDh", isHotzone = false, isCity = false},
        {shortName = "takj", fullName = "Takish-Hiz J", zem = { emu = 1.50, live = "--" }, levelMin = 65, levelMax = 75, expansion = "DoDh", isHotzone = true, isCity = false},
        {shortName = "templeveeshan", fullName = "Temple of Veeshan", zem = { emu = 1.33, live = "--" }, levelMin = 50, levelMax = 60, expansion = "Velious", isHotzone = true, isCity = false},
        {shortName = "tenebrous", fullName = "Tenebrous Mountains", zem = { emu = 1.75, live = "--" }, levelMin = 35, levelMax = 50, expansion = "Luclin", isHotzone = true, isCity = false},
        {shortName = "thalassius", fullName = "Thalassius, the Coral Keep", zem = { emu = 1.00, live = "--" }, levelMin = 75, levelMax = 85, expansion = "TBS", isHotzone = false, isCity = false},
        {shortName = "theater", fullName = "Theater of Blood", zem = { emu = 1.00, live = "--" }, levelMin = 65, levelMax = 75, expansion = "PoR", isHotzone = false, isCity = false},
        {shortName = "theatera", fullName = "Theater of Blood Annex", zem = { emu = 1.00, live = "--" }, levelMin = 65, levelMax = 75, expansion = "PoR", isHotzone = false, isCity = false},
        {shortName = "thedeep", fullName = "The Deep", zem = { emu = 2.00, live = "--" }, levelMin = 45, levelMax = 60, expansion = "Luclin", isHotzone = true, isCity = false},
        {shortName = "thegrey", fullName = "The Grey", zem = { emu = 2.00, live = "--" }, levelMin = 45, levelMax = 60, expansion = "Luclin", isHotzone = true, isCity = false},
        {shortName = "thenest", fullName = "The Nest", zem = { emu = 3.10, live = "--" }, levelMin = 60, levelMax = 70, expansion = "DoN", isHotzone = true, isCity = false},
        {shortName = "thevoida", fullName = "The Void A", zem = { emu = 1.50, live = "--" }, levelMin = 70, levelMax = 80, expansion = "SoF", isHotzone = true, isCity = false},
        {shortName = "thevoidb", fullName = "The Void B", zem = { emu = 1.50, live = "--" }, levelMin = 70, levelMax = 80, expansion = "SoF", isHotzone = true, isCity = false},
        {shortName = "thevoidc", fullName = "The Void C", zem = { emu = 1.50, live = "--" }, levelMin = 70, levelMax = 80, expansion = "SoF", isHotzone = true, isCity = false},
        {shortName = "thevoidd", fullName = "The Void D", zem = { emu = 1.50, live = "--" }, levelMin = 70, levelMax = 80, expansion = "SoF", isHotzone = true, isCity = false},
        {shortName = "thevoide", fullName = "The Void E", zem = { emu = 1.50, live = "--" }, levelMin = 70, levelMax = 80, expansion = "SoF", isHotzone = true, isCity = false},
        {shortName = "thevoidf", fullName = "The Void F", zem = { emu = 1.50, live = "--" }, levelMin = 70, levelMax = 80, expansion = "SoF", isHotzone = true, isCity = false},
        {shortName = "thevoidg", fullName = "The Void G", zem = { emu = 1.50, live = "--" }, levelMin = 70, levelMax = 80, expansion = "SoF", isHotzone = true, isCity = false},
        {shortName = "thrgadina", fullName = "Thurgadin", zem = { emu = 1.13, live = "--" }, levelMin = 30, levelMax = 50, expansion = "Velious", isHotzone = false, isCity = true},
        {shortName = "thurgadinb", fullName = "Thurgadin Depths", zem = { emu = 1.13, live = "--" }, levelMin = 30, levelMax = 50, expansion = "Velious", isHotzone = false, isCity = true},
        {shortName = "thundercrest", fullName = "Thundercrest Isles", zem = { emu = 3.05, live = "--" }, levelMin = 60, levelMax = 70, expansion = "DoN", isHotzone = true, isCity = false},
        {shortName = "timorous", fullName = "Timorous Deep", zem = { emu = 1.00, live = "--" }, levelMin = 10, levelMax = 30, expansion = "RoK", isHotzone = false, isCity = false},
        {shortName = "tipt", fullName = "Tipt, Treacherous Crags", zem = { emu = 2.00, live = "--" }, levelMin = 60, levelMax = 70, expansion = "GoD", isHotzone = true, isCity = false},
        {shortName = "torgiran", fullName = "Torgiran Mines", zem = { emu = 1.13, live = "--" }, levelMin = 45, levelMax = 60, expansion = "Luclin", isHotzone = false, isCity = false},
        {shortName = "toskirakk", fullName = "Toskirakk", zem = { emu = 1.50, live = "--" }, levelMin = 70, levelMax = 80, expansion = "SoF", isHotzone = true, isCity = false},
        {shortName = "tox", fullName = "Toxxulia Forest", zem = { emu = 1.00, live = "--" }, levelMin = 1, levelMax = 15, expansion = "Classic", isHotzone = false, isCity = false},
        {shortName = "toxxulia", fullName = "Toxxulia Forest", zem = { emu = 1.00, live = "--" }, levelMin = 1, levelMax = 15, expansion = "Classic", isHotzone = false, isCity = false},
        {shortName = "trakanon", fullName = "Trakanon's Teeth", zem = { emu = 1.00, live = "--" }, levelMin = 30, levelMax = 50, expansion = "RoK", isHotzone = false, isCity = false},
        {shortName = "tutorial", fullName = "Tutorial Zone", zem = { emu = 1.00, live = "--" }, levelMin = 1, levelMax = 10, expansion = "Classic", isHotzone = false, isCity = false},
        {shortName = "tutoriala", fullName = "Tutorial A", zem = { emu = 1.00, live = "--" }, levelMin = 1, levelMax = 10, expansion = "Classic", isHotzone = false, isCity = false},
        {shortName = "tutorialb", fullName = "Tutorial B", zem = { emu = 1.00, live = "--" }, levelMin = 1, levelMax = 10, expansion = "Classic", isHotzone = false, isCity = false},
        {shortName = "twilight", fullName = "Twilight Sea", zem = { emu = 1.00, live = "--" }, levelMin = 25, levelMax = 45, expansion = "Luclin", isHotzone = false, isCity = false},
        {shortName = "txevu", fullName = "Txevu, Lair of the Elite", zem = { emu = 1.75, live = "--" }, levelMin = 65, levelMax = 75, expansion = "GoD", isHotzone = true, isCity = false},
        {shortName = "umbral", fullName = "Umbral Plains", zem = { emu = 1.20, live = "--" }, levelMin = 50, levelMax = 65, expansion = "Luclin", isHotzone = true, isCity = false},
        {shortName = "unrest", fullName = "Estate of Unrest", zem = { emu = 1.73, live = "--" }, levelMin = 15, levelMax = 35, expansion = "Classic", isHotzone = true, isCity = false},
        {shortName = "uqua", fullName = "Uqua, the Ocean God Chantry", zem = { emu = 2.00, live = "--" }, levelMin = 65, levelMax = 75, expansion = "GoD", isHotzone = true, isCity = false},
        {shortName = "valdeholm", fullName = "Valdeholm", zem = { emu = 1.00, live = "--" }, levelMin = 70, levelMax = 80, expansion = "TSS", isHotzone = false, isCity = true},
        {shortName = "veeshan", fullName = "Veeshan's Peak", zem = { emu = 1.00, live = "--" }, levelMin = 50, levelMax = 65, expansion = "RoK", isHotzone = false, isCity = false},
        {shortName = "veksar", fullName = "Veksar", zem = { emu = 1.33, live = "--" }, levelMin = 40, levelMax = 55, expansion = "RoK", isHotzone = true, isCity = false},
        {shortName = "velketor", fullName = "Velketor's Labyrinth", zem = { emu = 1.50, live = "--" }, levelMin = 45, levelMax = 60, expansion = "Velious", isHotzone = true, isCity = false},
        {shortName = "vergalid", fullName = "Vergalid Mines", zem = { emu = 1.00, live = "--" }, levelMin = 65, levelMax = 75, expansion = "TSS", isHotzone = false, isCity = false},
        {shortName = "vexthal", fullName = "Vex Thal", zem = { emu = 1.33, live = "--" }, levelMin = 55, levelMax = 65, expansion = "Luclin", isHotzone = true, isCity = false},
        {shortName = "vxed", fullName = "Vxed, The Crumbling Caverns", zem = { emu = 2.00, live = "--" }, levelMin = 60, levelMax = 70, expansion = "GoD", isHotzone = true, isCity = false},
        {shortName = "wakening", fullName = "The Wakening Land", zem = { emu = 1.00, live = "--" }, levelMin = 35, levelMax = 50, expansion = "Velious", isHotzone = false, isCity = false},
        {shortName = "wallofslaughter", fullName = "Wall of Slaughter", zem = { emu = 2.50, live = "--" }, levelMin = 60, levelMax = 70, expansion = "OoW", isHotzone = true, isCity = false},
        {shortName = "warrens", fullName = "Warrens", zem = { emu = 2.00, live = "--" }, levelMin = 15, levelMax = 35, expansion = "RoK", isHotzone = true, isCity = false},
        {shortName = "warslikswood", fullName = "Warsliks Woods", zem = { emu = 1.00, live = "--" }, levelMin = 10, levelMax = 25, expansion = "RoK", isHotzone = false, isCity = false},
        {shortName = "westkorlach", fullName = "West Korlach", zem = { emu = 1.00, live = "--" }, levelMin = 60, levelMax = 75, expansion = "DoDh", isHotzone = false, isCity = false},
        {shortName = "westkorlacha", fullName = "West Korlach Depths A", zem = { emu = 1.00, live = "--" }, levelMin = 60, levelMax = 75, expansion = "DoDh", isHotzone = false, isCity = false},
        {shortName = "westkorlachb", fullName = "West Korlach Depths B", zem = { emu = 1.00, live = "--" }, levelMin = 60, levelMax = 75, expansion = "DoDh", isHotzone = false, isCity = false},
        {shortName = "westkorlachc", fullName = "West Korlach Depths C", zem = { emu = 1.00, live = "--" }, levelMin = 60, levelMax = 75, expansion = "DoDh", isHotzone = false, isCity = false},
        {shortName = "westwastes", fullName = "Western Wastes", zem = { emu = 1.06, live = "--" }, levelMin = 35, levelMax = 50, expansion = "Velious", isHotzone = false, isCity = false},
        {shortName = "yxtta", fullName = "Yxtta, Pulpit of Exiles", zem = { emu = 2.00, live = "--" }, levelMin = 60, levelMax = 70, expansion = "GoD", isHotzone = true, isCity = false},
        {shortName = "zhisza", fullName = "Zhisza, the Shissar Sanctuary", zem = { emu = 1.00, live = "--" }, levelMin = 60, levelMax = 75, expansion = "TBS", isHotzone = false, isCity = false},
        {shortName = "brellsrest", fullName = "Brell's Rest", zem = { emu = 1.00, live = "--" }, levelMin = 85, levelMax = 95, expansion = "Underfoot", isHotzone = false, isCity = false},
        {shortName = "coolingchamber", fullName = "Cooling Chamber", zem = { emu = 1.00, live = "--" }, levelMin = 85, levelMax = 95, expansion = "Underfoot", isHotzone = false, isCity = false},
        {shortName = "pellucid", fullName = "Pellucid Grotto", zem = { emu = 1.00, live = "--" }, levelMin = 85, levelMax = 95, expansion = "Underfoot", isHotzone = false, isCity = false},
        {shortName = "arthicrex", fullName = "Arthicrex", zem = { emu = 1.00, live = "--" }, levelMin = 85, levelMax = 95, expansion = "Underfoot", isHotzone = false, isCity = false},
        {shortName = "foundation", fullName = "Foundation", zem = { emu = 1.00, live = "--" }, levelMin = 85, levelMax = 95, expansion = "Underfoot", isHotzone = false, isCity = false},
        {shortName = "underquarry", fullName = "Underquarry", zem = { emu = 1.00, live = "--" }, levelMin = 85, levelMax = 95, expansion = "Underfoot", isHotzone = false, isCity = false},
        {shortName = "brellsarena", fullName = "Brell's Arena", zem = { emu = 1.00, live = "--" }, levelMin = 85, levelMax = 95, expansion = "Underfoot", isHotzone = false, isCity = false},
        {shortName = "stonesnake", fullName = "Stonesnake", zem = { emu = 1.00, live = "--" }, levelMin = 85, levelMax = 95, expansion = "Underfoot", isHotzone = false, isCity = false},
    },
    expansionOrder = { ["Classic"] = 1, ["RoK"] = 2, ["Velious"] = 3, ["Luclin"] = 4, ["PoP"] = 5, ["GoD"] = 6, ["DoN"] = 7, ["OoW"] = 8, ["DoDh"] = 9, ["TSS"] = 10, ["TBS"] = 11, ["SoF"] = 12, ["PoR"] = 13, ["RoF"] = 14, ["LoY"] = 15, ["Underfoot"] = 16, ["Live"] = 999 },
    expansionList = {"Classic", "RoK", "Velious", "Luclin", "PoP", "GoD", "DoN", "OoW", "DoDh", "TSS", "TBS", "SoF", "PoR", "RoF", "LoY", "Underfoot", "Live"}
}

return zones